variables:
  CREATEREPO_OPTS: -q -d

stages:
  - tools
  - prereqs
  - srpm
  - buildreqs
  - build
  - register

.macros: &macros
    - |
      cat <<-EOF> ${HOME}/.rpmmacros
      %dis            el
      %tro            $(rpm -qf --qf "%{version}" /etc/issue)
      %_topdir        %(pwd)

      #  (S)RPMs go to the staging area
      %_rpmdir       %{_topdir}/RPMS%{?apt:.%{apt}}
      %_srcrpmdir    %{_topdir}/SRPMS%{?apt:.%{apt}}
      
      #  Builds occur in a standard space
      %_builddir     %{_topdir}/BUILD
      
      #  Source and Spec under cvs area
      %_specdir      %{_topdir}/SPECS
      %_sourcedir    %{_topdir}/SOURCES

      %_build_name_fmt    %%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%{dis}%{tro}.%%{ARCH}.rpm
      EOF

.tags:
  tags:
    - rpm-build
  before_script:
    - *macros

tools:
  extends: .tags
  stage: tools
  script:
    - |
      sudo -n yum install -y rpm-build rpmdevtools
      #mkdir .junk ; rsync -a --delete .junk/ RPMS/ ; rsync -a --delete .junk/ SRPMS/

.makedirs:
  extends: .tags
  stage: prereqs
  script:
    - |
      echo     $(rpm --eval '%_sourcedir') \
               $(rpm --eval '%_rpmdir') \
               $(rpm --eval '%_srcrpmdir') \
               $(rpm --eval '%_builddir') \
               $(rpm --eval '%_specdir') \
      | xargs mkdir -pv
      spectool -g -R $(rpm --eval '%_specdir')/${SPECNAME:-nothing}.spec
      find SOURCES -ls
  cache:
    paths:
      - SOURCES/
  artifacts:
    paths:
      - SOURCES/

.get_BUILD_pre-reqs:
  extends: .tags
  stage: buildreqs
  script:
    - sudo -n yum-builddep -y $(rpm --eval '%_specdir')/${SPECNAME:-nothing}.spec --nogpgcheck
  artifacts:
    paths:
    - SRPMS/  

.build_SRPM:
  extends: .tags
  stage: srpm
  script:
    - rpmbuild -bs $(rpm --eval '%_specdir')/${SPECNAME:-nothing}.spec
  artifacts:
    paths:
    - SRPMS/

.build_RPM:
  extends: .tags
  stage: build
  script:
    - rpmbuild -bb $(rpm --eval '%_specdir')/${SPECNAME:-nothing}.spec 
  artifacts:
    paths:
    - SRPMS/
    - RPMS/

repo:
  tags:
    - repo
  stage: register
  before_script:
    - *macros
    - sudo -n yum install -y createrepo --nogpgcheck
  script:
    - |
      TREE=${CI_COMMIT_REF_SLUG}/$(rpm --eval "%dis/%tro")
      PUBROOT=~/public_html/${TREE}/
      mkdir -p ${PUBROOT}
      # push any artifacts to service dir
      find . \
        -name \*RPMS -type d \
        -exec rsync -av {} ${PUBROOT} \;
      # createrepo the lot
      find ${PUBROOT} \
        -name \*RPMS -type d \
        -exec createrepo ${CREATEREPO_OPTS:-} ${ADDL_OPTS:-} {} \;
  artifacts: {}

